version: '3.8'

services:
  dev-helper:
    build:
      context: .
      dockerfile: Dockerfile
    image: dev-helper:latest
    container_name: dev-helper-container
    ports:
      - "4201:4201"
    restart: unless-stopped
    extra_hosts:
      - "argocd.cloudsolutions.com.sa:10.201.206.70"
      - "eureka.cloudsolutions.com.sa:10.201.206.70"
      - "sonarqube.cloudsolutions.lk:10.200.222.160"
      - "registry.cloudsolutions.com.sa:10.201.206.83"
      - "argo.hmg.com.sa:10.201.216.99"
      - "argo.hmg.com:10.201.216.99"
      - "nexusrepo-java.cloudsolutions.lk:10.200.222.157"
      - "nexusrepo-net.cloudsolutions.lk:10.200.222.158"
      - "scinstallcheck.mcafee.com:0.0.0.1"
      - "mail.drsulaimanalhabib.com:10.200.200.71"
      - "argomchisu.kku.edu.sa:10.3.134.100"
      - "mchisu.kku.edu.sa:10.3.134.100"
      - "nexusrepo-java-new.cloudsolutions.lk:10.201.206.172"
      - "argomchis.kkuprod.edu.sa:10.3.108.100"
      - "mchis.kku.edu.sa:10.3.108.100"
      - "vidaprod.hmg.com:10.201.218.10"
      - "umm.moh.gov.sa:10.4.41.170"
      - "emdaa.moh.gov.sa:10.4.41.170"
      - "config.moh.gov.sa:10.4.41.170"
      - "eureka.moh.gov.sa:10.4.41.170"
      - "apphiss2viu.moh.gov.sa:10.4.41.170"
      - "apphiss2sit.moh.gov.sa:10.4.41.170"
      - "argos2.moh.gov.sa:10.4.41.170"
      - "apphiss3viu.moh.gov.sa:10.4.42.150"
      - "eurekas3uat.moh.gov.sa:10.4.42.150"
      - "polaris3moh.gov.sa:10.4.42.150"
      - "goldilocks3moh.gov.sa:10.4.42.150"
      - "argos3.moh.gov.sa:10.4.42.150"
      - "vidapreprod.hmg.com:10.201.216.99"
      - "vidauat.cloudsolutions.com.sa:10.201.216.20"
      - "jazanupreprod.cloudsolutions.com.sa:141.147.136.201"
      - "argocd-oci.cloudsolutions.com.sa:141.147.136.201"
      - "linkerd.dev.cloudsolution.lk:172.15.100.87"
      - "argocd-vidauat.cloudsolutions.com.sa:10.201.216.10"
      - "nova.cloudsolutions.lk:35.247.160.145"
      - "mssplus.mcafee.com:0.0.0.1"
      - "host.docker.internal:172.15.10.85"
      - "gateway.docker.internal:172.15.10.85"
      - "kubernetes.docker.internal:127.0.0.1"
      - "prod-aseer-argo.moh.gov.sa:10.9.97.131"
      - "apphiss1vi.moh.gov.sa:10.9.97.131"
      - "dbtools-aseer-prod.cloudsolutions.com.sa:10.9.97.131"
      - "ie-dashboards-aseer-prod.cloudsolutions.com.sa:10.9.97.131"
      - "csprod-argo.cloudsolutions.com.sa:8.213.37.89"
      - "qiddiya.cloudsolutions.com.sa:8.213.37.89"
      - "oncology.cloudsolutions.com.sa:8.213.37.89"
      - "rsgairport.cloudsolutions.com.sa:8.213.37.89"
      - "csi.dev.cloudsol.lk:10.201.216.151"
      - "dev.cloudsolutions.com.sa:10.201.216.151"
      - "dev-argocd.cloudsolutions.com.sa:10.201.216.151"
      - "argos3-prod.moh.gov.sa:10.4.42.155"
      - "apphiss3vi.moh.gov.sa:10.4.42.155"
      - "apphisw1vi.moh.gov.sa:10.4.62.100"
      - "argo-prod.kfsh.com.sa:10.4.62.100"
      - "apphisw1viu.moh.gov.sa:10.4.62.109"
      - "argo.kfsh.com.sa:10.4.62.109"
      - "argocdnew.kaauh.org:10.9.205.148"
      - "kauhvidau.kaauh.org:10.9.205.148"
      - "csiquat.cloudsolutions.com.sa:172.15.100.231"
      - "aseer-argo.moh.gov.sa:10.8.113.229"
      - "apphiss1viu.moh.gov.sa:10.8.113.229"
      - "orodruin.cloudsolutions.com.sa:10.201.206.70"
      - "his.kaauh.org:10.9.205.140"
      - "argocd-prod.kaauh.org:10.9.205.140"
      - "argo-salespoc.cloudsolutions.com.sa:8.213.46.8"
      - "csi.featuretoggles.com:172.15.100.145"
      - "apphiss2vi.moh.gov.sa:10.4.41.10"
      - "lynx.hmg.com:10.201.208.4"
      - "cs-agents.cloudsolutions.com.sa:172.15.100.210"
      - "hmguat.cloudsolutions.com.sa:10.201.216.20"
      - "argocd-vidauat2.cloudsolutions.com.sa:10.201.216.20"
      - "vidapoc.cloudsolutions.com.sa:10.7.33.190"
